from typing import Any

import io

class IndexedGzipFile(io.BufferedReader):
    auto_build: Any = ...
    closed: Any = ...
    drop_handles: Any = ...
    filename: Any = ...
    mode: Any = ...
    own_file: Any = ...
    readall_buf_size: Any = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def __file_handle(self) -> Any: ...
    def build_full_index(self) -> Any: ...
    def close(self) -> Any: ...
    def export_index(self, filename = ..., fileobj = ...) -> Any: ...
    def fileno(self) -> Any: ...
    def fileobj(self) -> Any: ...
    def flush(self) -> Any: ...
    def import_index(self, filename = ..., fileobj = ...) -> Any: ...
    def pread(self, nbytes, offset) -> Any: ...
    def read(self, nbytes = int) -> Any: ...
    def readable(self) -> Any: ...
    def readinto(self, buf) -> Any: ...
    def readline(self, size = ...) -> Any: ...
    def readlines(self, hint = ...) -> Any: ...
    def seek(self, offset, whence = ...) -> Any: ...
    def seekable(self) -> Any: ...
    def tell(self) -> Any: ...
    def writable(self) -> Any: ...
    def write(self, *args, **kwargs) -> Any: ...
    def __enter__(self) -> Any: ...
    def __exit__(self, *args) -> Any: ...
    def __iter__(self) -> Any: ...
    def __next__(self) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...
